// generated by stringer -type=Direction; DO NOT EDIT

package gpio

import "fmt"

const _Direction_name = "DirInDirOut"

var _Direction_index = [...]uint8{0, 5, 11}

func (i Direction) String() string {
	if i < 0 || i+1 >= Direction(len(_Direction_index)) {
		return fmt.Sprintf("Direction(%d)", i)
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
