// generated by stringer -type=EdgeTrigger; DO NOT EDIT

package gpio

import "fmt"

const _EdgeTrigger_name = "EdgeNoneEdgeRisingEdgeFallingEdgeBoth"

var _EdgeTrigger_index = [...]uint8{0, 8, 18, 29, 37}

func (i EdgeTrigger) String() string {
	if i < 0 || i+1 >= EdgeTrigger(len(_EdgeTrigger_index)) {
		return fmt.Sprintf("EdgeTrigger(%d)", i)
	}
	return _EdgeTrigger_name[_EdgeTrigger_index[i]:_EdgeTrigger_index[i+1]]
}
