// generated by stringer -type=Pull; DO NOT EDIT

package gpio

import "fmt"

const _Pull_name = "PullOffPullDownPullUp"

var _Pull_index = [...]uint8{0, 7, 15, 21}

func (i Pull) String() string {
	if i < 0 || i+1 >= Pull(len(_Pull_index)) {
		return fmt.Sprintf("Pull(%d)", i)
	}
	return _Pull_name[_Pull_index[i]:_Pull_index[i+1]]
}
