// generated by stringer -type=Trigger; DO NOT EDIT

package gpio

import "fmt"

const _Trigger_name = "EdgeNoneEdgeRisingEdgeFallingEdgeBoth"

var _Trigger_index = [...]uint8{0, 8, 18, 29, 37}

func (i Trigger) String() string {
	if i < 0 || i+1 >= Trigger(len(_Trigger_index)) {
		return fmt.Sprintf("Trigger(%d)", i)
	}
	return _Trigger_name[_Trigger_index[i]:_Trigger_index[i+1]]
}
